base_url = "https://blog.cronbox.ru"

compile_sass = true

highlight_code = true

build_search_index = true

theme = "tinyblog"

generate_rss = true

title = "Блог Cronbox"
description = "О мониторинге, cron и технологиях"

taxonomies = [
 {name = "tags", rss = true},
 {name = "categories", paginate_by = 5, rss = true},
 {name = "authors"}
]

[extra]
description = "Мониторинг cron задач"

website="cronbox.ru"
website_button_hint = "Перейти на cronbox.ru"

twitter=""
twitter_button_hint = ""

email = ""
email_button_hint = ""

github_button_hint = ""

favicon_type = "image/vnd.microsoft.icon"

open_graph_url = "https://blog.cronbox.ru"
open_graph_type = "blog"
open_graph_title = "Блог Cronbox"
open_graph_description = "Блог о мониторинге, cron и технологиях"
open_graph_image = ""
