base_url = "https://blog.cronbox.ru"

compile_sass = true

highlight_code = true

build_search_index = true

theme = "tinyblog"

generate_feed = true
feed_limit = 100

title = "Блог Cronbox"
description = "О мониторинге, cron и технологиях"

taxonomies = [
 {name = "tags"},
 {name = "categories", paginate_by = 5},
 {name = "authors"}
]

[extra]
description = "Мониторинг cron задач"
keywords = "мониторинг задач, мониторинг cron, мониторинг резервного копирования, мониторинг бэкапов, cron"

website="cronbox.ru"
website_button_hint = "Перейти на cronbox.ru"
website_button_title = "Сайт"

twitter=""
twitter_button_hint = ""

email = ""
email_button_title = "Написать на почту"
email_button_hint = ""

github_button_hint = ""

favicon_type = "image/vnd.microsoft.icon"

open_graph_url = "https://blog.cronbox.ru"
open_graph_type = "blog"
open_graph_title = "Блог Cronbox"
open_graph_description = "Блог о мониторинге, cron и технологиях"
open_graph_image = ""

#----------------------------------------------
# YANDEX
#----------------------------------------------
# Yandex.WebMaster
yandex_webmaster_verification_code = "7e31b2e5536fb5d8"

# Yandex Metrika
yandex_metrika_counter = "64400824"
